#
# K8S_VER = ""
K8S_VER = "1.26.9"
K8S_VIP = "192.168.56.30"
UBU_VER = "ubuntu/focal64" # 20.04
# UBU_VER = "ubuntu/jammy64" # 22.04
#
#
# Calculated Variables
K8S_IP_A = K8S_VIP.chop
K8S_IP_B = K8S_VIP.slice(-1)
K8S_CP_IP1 = K8S_IP_A + K8S_IP_B.succ
K8S_CP_IP2 = K8S_IP_A + K8S_IP_B.succ.succ
K8S_CP_IP3 = K8S_IP_A + K8S_IP_B.succ.succ.succ
K8S_W_IP1 = K8S_IP_A + K8S_IP_B.succ.succ.succ.succ
K8S_W_IP2 = K8S_IP_A + K8S_IP_B.succ.succ.succ.succ.succ
K8S_W_IP3 = K8S_IP_A + K8S_IP_B.succ.succ.succ.succ.succ.succ

K8S_CP_IPs = Array[K8S_CP_IP1, K8S_CP_IP2, K8S_CP_IP3]
K8S_W_IPs = Array[K8S_W_IP1, K8S_W_IP2, K8S_W_IP3]



K8S_IF = "enp0s8"
#
#
$os_init_script = <<-SCRIPT_Init_OS
echo ">------------------------------ RSA keys ------------------------------<"
if [ ! -f "/vagrant/vagrant_id_rsa.pub"  ] ||  [ ! -f "/vagrant/vagrant_id_rsa" ]
then
  ssh-keygen -f $HOME/.ssh/id_rsa -P ""
  cp $HOME/.ssh/id_rsa /vagrant/vagrant_id_rsa
  cp $HOME/.ssh/id_rsa.pub /vagrant/vagrant_id_rsa.pub
else
  cp /vagrant/vagrant_id_rsa $HOME/.ssh/id_rsa
  cp /vagrant/vagrant_id_rsa.pub $HOME/.ssh/id_rsa.pub
fi
cp $HOME/.ssh/id_rsa.pub $HOME/.ssh/authorized_keys

echo ">------------------------------ OS update ------------------------------<"
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get upgrade -y

echo ">------------------------------ setup /etc/hosts ------------------------------<"
sed -i '/cp/d' /etc/hosts
echo $1  k8scp  cp >> /etc/hosts
echo $2  worker >> /etc/hosts
echo $3  student >> /etc/hosts

echo ">------------------------------ setup .bashrc ------------------------------<"
runuser -l vagrant -c 'echo "sudo -i"  >> $HOME/.bashrc'

apt-get install bash-completion -y
#source <(kubectl completion bash)
echo "source <(kubectl completion bash)" >> $HOME/.bashrc
echo "alias k=kubectl" >> $HOME/.bashrc
echo "complete -F __start_kubectl k" >> $HOME/.bashrc

SCRIPT_Init_OS
#
#
$install_script = <<-SCRIPT
echo "---------------------------------------------------------------------------------"
echo " 1: " $1
echo " 2: " $2
echo " 3: " $3
echo " 4: " $4
echo "---------------------------------------------------------------------------------"
echo "script_all_1"
echo "---------------------------------------------------------------------------------"
apt-get update && apt-get upgrade -y
apt-get install -y vim bash-completion jq
sed -i "/$HOSTNAME/d" /etc/hosts
echo '192.168.56.30  k8svip' >> /etc/hosts
echo '192.168.56.31  cp1' >> /etc/hosts
echo '192.168.56.32  cp2' >> /etc/hosts
echo '192.168.56.33  cp3' >> /etc/hosts
echo '192.168.56.41  worker1' >> /etc/hosts
echo '192.168.56.42  worker2' >> /etc/hosts
echo '192.168.56.43  worker3' >> /etc/hosts
echo '192.168.56.50  student' >> /etc/hosts
echo "      routes:" >> /etc/netplan/50-vagrant.yaml
echo "      - to: 10.96.0.0/12" >> /etc/netplan/50-vagrant.yaml
echo "        via: 192.168.56.31" >> /etc/netplan/50-vagrant.yaml
netplan apply
shopt -s expand_aliases
KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
alias kube-vip="ctr image pull ghcr.io/kube-vip/kube-vip:$KVVERSION; ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:$KVVERSION vip /kube-vip"
echo 'shopt -s expand_aliases' > /root/kube-vip.sh
echo 'KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")' >> /root/kube-vip.sh
echo 'alias kube-vip="ctr image pull ghcr.io/kube-vip/kube-vip:$KVVERSION; ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:$KVVERSION vip /kube-vip"' >> /root/kube-vip.sh
echo "kube-vip manifest daemonset --interface $4 --address $3 --inCluster --taint --controlplane --services --arp --leaderElection | kubectl apply -f - " >> /root/kube-vip.sh
if [ $1 != "student" ]; then 
  echo "---------------------------------------------------------------------------------"
  echo "script_cluster"
  echo "---------------------------------------------------------------------------------"
  apt-get install curl apt-transport-https vim git wget gnupg2 software-properties-common apt-transport-https ca-certificates uidmap -y
  swapoff -a
  modprobe overlay
  modprobe br_netfilter
  echo overlay > /etc/modprobe.d/kubernetes.conf
  echo br_netfilter >> /etc/modprobe.d/kubernetes.conf
  echo 'net.bridge.bridge-nf-call-ip6tables = 1' >> /etc/sysctl.d/kubernetes.conf
  echo 'net.bridge.bridge-nf-call-iptables = 1' >> /etc/sysctl.d/kubernetes.conf
  echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.d/kubernetes.conf
  sysctl --system
  sudo mkdir -m 0755 -p /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt update && apt-get install containerd.io -y
  sed -e '/cri/ s/^#*/#/' -i /etc/containerd/config.toml 
  systemctl restart containerd.service 
  echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list
  curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  apt-get update 
  apt-get install -y kubeadm=$2-00 kubelet=$2-00 kubectl=$2-00 etcd-client
  apt-mark hold kubelet kubeadm kubectl
  echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> /root/.bashrc
  runuser -l vagrant -c 'echo "sudo -i" >> $HOME/.bashrc'
  if [ $1 = "cp1" ]; then 
    echo "---------------------------------------------------------------------------------"
    echo "script_first_node"
    echo "---------------------------------------------------------------------------------"
    sed -i 's/192.168.56.30/192.168.56.31/' /etc/hosts
    kubeadm init --apiserver-advertise-address=192.168.56.31 --pod-network-cidr=10.244.0.0/16 --apiserver-cert-extra-sans k8svip,192.168.56.30 --control-plane-endpoint k8svip:6443 --upload-certs --kubernetes-version $2 | tee /root/kubeadm-cp1-init.out
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
    kubeadm token create --print-join-command > /vagrant/kubeadm_join_worker.sh
    kubeadm token create --print-join-command | tr -d '\n' > /vagrant/kubeadm_join_cp.sh
    echo -n ' --apiserver-advertise-address $(hostname -I | cut -d " " -f 2)  --control-plane --certificate-key '  >> /vagrant/kubeadm_join_cp.sh
    kubeadm init phase upload-certs --upload-certs | tail -n 1 >> /vagrant/kubeadm_join_cp.sh
    kubectl get all -A
    #KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
    #echo $KVVERSION
    #alias kube-vip="ctr image pull ghcr.io/kube-vip/kube-vip:$KVVERSION; ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:$KVVERSION vip /kube-vip"
    #alias
    #echo "kube-vip manifest daemonset --interface $4 --address $3 --inCluster --taint --controlplane --services --arp --leaderElection | kubectl apply -f - "
    #sleep 120
    #kubectl get all -A
    #kube-vip manifest daemonset --interface $4 --address $3 --inCluster --taint --controlplane --services --arp --leaderElection | kubectl apply -f -
    bash /root/kube-vip.sh
    sudo cp /etc/kubernetes/admin.conf /vagrant
    sed -i 's/192.168.56.31  k8svip/192.168.56.30  k8svip/' /etc/hosts
  elif [ $1 = "cp2" -o $1 = "cp3" ]; then 
    echo "---------------------------------------------------------------------------------"
    echo "script_next_cluster_node"
    echo "---------------------------------------------------------------------------------"
    cp /vagrant/admin.conf /etc/kubernetes
    export KUBECONFIG=/etc/kubernetes/admin.conf
    sh /vagrant/kubeadm_join_cp.sh
  elif [[ $1 == "worker"* ]]; then 
    echo "---------------------------------------------------------------------------------"
    echo "script_worker"
    echo "---------------------------------------------------------------------------------"
    cp /vagrant/admin.conf /etc/kubernetes
    export KUBECONFIG=/etc/kubernetes/admin.conf
    sh /vagrant/kubeadm_join_worker.sh
  fi
else 
  echo "---------------------------------------------------------------------------------"
  echo "script_student"
  echo "---------------------------------------------------------------------------------"
  useradd -m -s /bin/bash -p sakZ/dnex68yw student
  echo 'student ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/student
  chmod 440 /etc/sudoers.d/student
  mkdir -p $HOME/.kube
  runuser -l student -c 'mkdir -p $HOME/.kube'
  runuser -l student -c 'mkdir -p $HOME/.kube'
  runuser -l student -c 'sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config'
  runuser -l student -c 'sudo chown $(id -u):$(id -g) $HOME/.kube/config'
  #
  runuser -l student -c 'echo "source <(kubectl completion bash)" >> $HOME/.bashrc'
  runuser -l student -c 'echo "source <(kubeadm completion bash)" >> $HOME/.bashrc'
  runuser -l student -c 'echo "alias k=kubectl" >> $HOME/.bashrc'
  runuser -l student -c 'echo "complete -F __start_kubectl k" >> $HOME/.bashrc'
  runuser -l vagrant -c 'echo "sudo su - student" >> $HOME/.bashrc'
fi
echo "---------------------------------------------------------------------------------"
echo "script_all_2"
echo "---------------------------------------------------------------------------------"
echo "source <(kubectl completion bash)" >> $HOME/.bashrc
echo "source <(kubeadm completion bash)" >> $HOME/.bashrc
echo "alias k=kubectl" >> $HOME/.bashrc
echo "complete -F __start_kubectl k" >> $HOME/.bashrc
SCRIPT
#
#
#
Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "cp#{i}" do |node|
      node.vm.box = UBU_VER
      node.vm.network "private_network", ip: "192.168.56.3#{i}"
      node.vm.hostname = "cp#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
      end
      node.vm.provision "shell", args: K8S_IPs, inline: $os_init_script
      #node.vm.provision "shell", args: K8S_VER, inline: $k8s_install_script
      #node.vm.provision "shell", args: K8S_VIP, inline: $k8s_cluster_init_script
      #node.vm.provision "shell", inline: $k8s_node_configure_script
      #node.vm.provision "shell", args: ["cp#{i}","#{K8S_VER}","#{K8S_VIP}","#{K8S_IF}"],  inline: $install_script
    end
  end

  (1..3).each do |i|
    config.vm.define "worker#{i}" do |node|
      node.vm.box = "#{UBU_VER}"
      node.vm.network "private_network", ip: "192.168.56.4#{i}"
      node.vm.hostname = "worker#{i}"

      config.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
      end
      node.vm.provision "shell", args: K8S_IPs, inline: $os_init_script
      #node.vm.provision "shell", args: K8S_VER, inline: $k8s_install_script
      #node.vm.provision "shell", args: K8S_VIP, inline: $k8s_worker_init_script
      #node.vm.provision "shell", inline: $k8s_node_configure_script
      #node.vm.provision "shell", args: ["worker#{i}","#{K8S_VER}","#{K8S_VIP}","#{K8S_IF}"],  inline: $install_script
    end
  end

  config.vm.define "student" do |student|
    student.vm.box = "#{UBU_VER}"
    student.vm.network "private_network", ip: "192.168.56.50"
    student.vm.hostname = "student"
    student.vm.provision "shell", args: K8S_IPs, inline: $os_init_script
    #student.vm.provision "shell", args: K8S_VER, inline: $k8s_student_init_script
    #student.vm.provision "shell", args: ["student","#{K8S_VER}","#{K8S_VIP}","#{K8S_IF}"],  inline: $install_script
  end
end
