Vagrant.configure("2") do |config|
  config.vm.define "srv1" do |node|
    node.vm.box = "centos/7"
    node.vm.network "private_network", ip: "192.168.56.11"
    node.vm.hostname = "srv1"
  end

  config.vm.define "srv2" do |node|
    node.vm.box = "centos/7"
    node.vm.network "private_network", ip: "192.168.56.12"
    node.vm.hostname = "srv2"
  end

  config.vm.define "srv3" do |node|
    node.vm.box = "centos/7"
    node.vm.network "private_network", ip: "192.168.56.13"
    node.vm.hostname = "srv3"
  end
end
