Vagrant.configure("2") do |config|
  config.vm.define "srv1" do |node|
    node.vm.box = "generic/oracle8"
    node.vm.network "private_network", ip: "192.168.56.101"
    node.vm.hostname = "srv1"
    node.vm.synced_folder ".", "/vagrant"
    node.vm.provision "shell", inline: <<-SHELLCP
      firewall-cmd --add-port=4505/tcp --permanent
      firewall-cmd --add-port=4506/tcp --permanent
      firewall-cmd --reload 
      curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
      sh bootstrap-salt.sh -M -A 192.168.56.101
      echo "auto_accept: True " > /etc/salt/master.d/auto_accept_minions.conf
      systemctl restart salt-master.service
      systemctl restart salt-minion.service
    SHELLCP
  end

  config.vm.define "srv2" do |node|
    node.vm.box = "generic/oracle8"
    node.vm.network "private_network", ip: "192.168.56.102"
    node.vm.hostname = "srv2"
    node.vm.synced_folder ".", "/vagrant"
    node.vm.provision "shell", inline: <<-SHELLCP
      curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
      sh bootstrap-salt.sh -A 192.168.56.101
    SHELLCP
  end

  config.vm.define "srv3" do |node|
    node.vm.box = "generic/oracle8"
    node.vm.network "private_network", ip: "192.168.56.103"
    node.vm.hostname = "srv3"
    node.vm.synced_folder ".", "/vagrant"
    node.vm.provision "shell", inline: <<-SHELLCP
      curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
      sh bootstrap-salt.sh -A 192.168.56.101
    SHELLCP
  end
end
