# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.ssh.insert_key = "false"

  config.vm.define "vm" do |vm|
    vm.vm.box = "tftp.bios.box"
    config.vm.provider :virtualbox do |vb|
      vb.name = "tftp.bios.test"
      vb.gui = true
    end
  end

  # config.vm.define "vm" do |vm|
  #   vm.vm.box = "tftp.efi.box"
  #   config.vm.provider :virtualbox do |vb|
  #     vb.name = "tftp.eft.test"
  #     vb.gui = true
  #   end
  # end

end
